version: '2'
services:
  Desktop-1:
    environment:
    - PASSWORD=password
    - USER=user
    cap_add:
    - SYS_PTRACE
    image: vdi:xfce
    stdin_open: true
    tty: true
    ports:
    - 4001:4000/tcp
    - 4443:4443/tcp
    - 4080:4080/tcp
    volumes:
    - ${PWD}/volumes/home:/home
