version: "3.5"
services:
  app:
    image: vdi:latest
    networks:
    - backend:
   

    environment:
    - PASSWORD=password
    - USER=user
    - KEYMAP="de"

    cap_add:
    - SYS_PTRACE
    stdin_open: true
    tty: true

    ports:
    - published: 4000
    - target: 4000

    volumes:
     - ./configs/server.cfg:/usr/NX/etc/server.cfg
     - ./configs/node.cfg:/usr/NX/etc/node.cfg
     - ./configs/bash_profile:/home/user/.bash_profile   # for keyboard layout
     - ./configs/xfce4:/home/user/.config/xfce4          # XFCE4 config; setup for Desktop Look&Feel
     - ./volumes/home:/home
     - ./volumes/Downloads:/home/user/Downloads
     - /tmp/1/Downloads:/home/user/Downloads

    labels:
      - "traefik.docker.network=backend"
      - "traefik.domain=vdi.dtpnk.tech"
      - "traefik.frontend.rule=Host:vdi.dtpnk.tech"
      - "traefik.enable=true"
      - "traefik.port=4080"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.whiteList.useXForwardedFor=true"

networks:
  backend:
